[package]
name = "reshell"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"
opt-level = 1
overflow-checks = false
debug = false

[profile.release]
panic = "abort"
debug = false

[dependencies]

